language: php
php: [nightly,7.4,7.3,7.2,7.1,5.6,5.5,5.4]
script: php "_okay.php" | diff ".expected${VERS}" -
matrix:
#  fast_finish: true
  include:
    - php: 5.3
      dist: precise
      env: VERS=5.3
  allow_failures:
  - php: 7.4