language: php
 
script: php "_okay.php" | tail -n +3 | diff -bwB ".expected${VERS}" -
#script: php "_okay.php" -D

matrix:
#  fast_finish: true
  include:
    - php: 5.3
      dist: precise
      env: VERS=5.3
    - php: 7.3
    - php: 7.4snapshot
    - php: 7.2
    - php: 7.1
    - php: 7.0
    - php: 5.4
      dist: trusty
    - php: 5.5
      dist: trusty
    - php: nightly
  allow_failures:
  - php: nightly