# Inspiration
# https://github.com/sebastianbergmann/phpunit/blob/main/.github/workflows/ci.yml

name: Okay self test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  tests:
    name: Tests

    runs-on: ${{ matrix.os }}

    env:
      PHP_INI_VALUES: assert.exception=0, memory_limit=-1, zend.assertions=1

    strategy:
      fail-fast: false
      matrix:
        os:
#          - ubuntu-latest
          - windows-latest

        php-version:
          - "8.1"
          # - "8.2"
          # - "5.3"
          # - "5.4"
          # - "5.5"
          # - "7.1"
          # - "7.4"

        compiler:
          - default

    defaults:
      run:
        shell: bash

    steps:

      - name: Configure git to avoid issues with line endings
        if: matrix.os == 'windows-latest'
        run: git config --global core.autocrlf false

      - name: Checkout
        uses: actions/checkout@v2

      - name: Override PHP ini values for JIT compiler
        if: matrix.compiler == 'jit'
        run: echo "PHP_INI_VALUES::assert.exception=0, memory_limit=-1, zend.assertions=1, opcache.enable=1, opcache.enable_cli=1, opcache.optimization_level=-1, opcache.jit=1255, opcache.jit_buffer_size=32M" >> $GITHUB_ENV

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          ini-values: ${{ env.PHP_INI_VALUES }}

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Run okay test suite
        run: php _okay.php || true

      - name: PHP5.x Different output
        if: startsWith(matrix.php-version, '5.')
        run: |
          echo "EXPECTED=expected5" >> $GITHUB_ENV

      - name: PHP5.3 Different output
        if: matrix.php-version == '5.3'
        run: |
          echo "EXPECTED=expected5.3" >> $GITHUB_ENV

      - name: ls
        run: ls -l

      - name: find
        run: find .

      - name: vars
        run: echo $EXPECTED

      - name: Regression
        run: composer run-script regression
